[agent]
  interval = "10s"
  round_interval = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "KOOvFhBiuao9q0CmH7DlU6Ka3_Q19nyvTTwYgbLm0EMl_WcyWCNO4JuPG_4HuvGkimwe1yMBV-tBInR2McWXBg=="
  organization = "Secondspark"
  bucket = "mazly"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["sensors/esp32_01"]
  data_format = "json"
