[agent]
  interval = "10s"
  round_interval = true
  debug = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "Ah89PHWEm5j8dIIjAH4cKyQwARelf2dQCa6hbSkJPMxic6Tida_j0adFxAVoA0J3Kdc7CIvFPOMHPTwgascf3Q=="
  organization = "Secondspark"
  bucket = "mazly"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["sensors/+"]
  data_format = "json_v2"
  name_override = "air_quality"
  topic_tag = "topic"


  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pm25"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pm10"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "co2"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "tvoc"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temp"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "hum"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "hcho"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "co"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "o3"
      type = "float"
      optional = true
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "no2"
      type = "float"
      optional = true
