; PlatformIO Project Configuration File
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 115200
monitor_speed = 115200

upload_flags = 
    --before=default_reset
    --after=hard_reset

lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    makuna/Rtc@^2.4.3
    bodmer/TFT_eSPI@^2.5.43
    ; adafruit/Adafruit GFX Library@^1.11.9 ; Optional, TFT_eSPI has its own GFX

build_flags =
    ; Tell TFT_eSPI to use these settings instead of the User_Setup.h file
    -D USER_SETUP_LOADED=1
    
    ; Driver and Interface for your 3.5" Screen
    -D RM68140_DRIVER=1
    -D ESP32_PARALLEL=1
    
    ; Control Pin Mapping
    -D TFT_CS=33
    -D TFT_DC=15
    -D TFT_RST=32
    -D TFT_WR=4
    -D TFT_RD=2
    
    ; 8-bit Data Bus Mapping (Must be GPIOs 0-31)
    -D TFT_D0=12
    -D TFT_D1=13
    -D TFT_D2=18
    -D TFT_D3=19
    -D TFT_D4=21
    -D TFT_D5=22
    -D TFT_D6=23
    -D TFT_D7=25
    
    ; Fonts to load
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
